name: Json Rest Server
port: 8080
host: 192.168.1.184
#host: 192.168.0.2 
#host: 192.168.0.14
#host: 0.0.0.0
database: database.json

auth:
  jwtSecret: cwsMXDtuP447WZQ63nM4dWZ3RppyMl
  jwtExpire: 3600
  unauthorizedStatusCode: 403
  urlSkip:
    - /images/:
       method: get
    - /users:
       method: post
