// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw4V07Qo7hwW4K6m0n006gY2C0fOO5Hts',
    appId: '1:680393092729:web:fed0708c53a7efb054aea8',
    messagingSenderId: '680393092729',
    projectId: 'myclinic-appv1',
    authDomain: 'myclinic-appv1.firebaseapp.com',
    storageBucket: 'myclinic-appv1.appspot.com',
    measurementId: 'G-RHT3R57EX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxwjCgUn5XPTIwb1169gUz7nmGgjucA38',
    appId: '1:680393092729:android:110b9a01a3be22fd54aea8',
    messagingSenderId: '680393092729',
    projectId: 'myclinic-appv1',
    storageBucket: 'myclinic-appv1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACwVONVGEHGRnnk4ycWDDcXfL3LFYSoeM',
    appId: '1:680393092729:ios:4c7866e8b39ef5d754aea8',
    messagingSenderId: '680393092729',
    projectId: 'myclinic-appv1',
    storageBucket: 'myclinic-appv1.appspot.com',
    iosBundleId: 'com.example.tccApp',
  );
}
